config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users, only: [:show]
  resources :registered_applications
  root to: 'welcome#index'

  namespace :api, defaults: { format: :json } do
    match 'events', to: 'events#index', via: [:options]
    resources :events, only: [:create]
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  validates :url, uniqueness: true, presence: true
  
  belongs_to :user
  has_many :events, dependent: :destroy

  before_validation :fix_url

  scope :visible_to, -> (user) { RegisteredApplication.where(user: user) }

  private

  def fix_url
    unless url.match(/https?:\/\//)
      self.url = "http://#{self.url}"
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications, dependent: :destroy
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_filter :set_access_control_headers

  def index
    render nothing: true, status: :ok
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application.nil?
      render json: "Unregistered application", status: :unprocessable_entity
    else

      @event = registered_application.events.build(event_params)
      if @event.save
        render json: @event, status: :created
      else
        render @event.errors, status: :unprocessable_entity
      end
    end
  end

  private

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type, application/json'
  end

  def event_params
    params.permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(user)
    registered_applications_path
  end
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = RegisteredApplication.visible_to current_user
  end

  def show
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def new
    @registered_application = RegisteredApplication.new
  end

  def create
    @registered_application = RegisteredApplication.new(registered_application_params)
    @registered_application.user = current_user
    if @registered_application.save
      flash[:notice] = "Registered \"#{@registered_application.name}\" successfully."
      redirect_to @registered_application
    else
      flash[:error] = "There was an error creating a registered application. Please try again."
      redirect_to registered_applications_path
    end
  end

  def edit
    @registered_application = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_application = RegisteredApplication.find(params[:id])
    if @registered_application.update_attributes(registered_application_params)
      flash[:notice] = "Updated \"#{@registered_application.name}\" successfully."
      redirect_to @registered_application
    else
      flash[:error] = "There was an error updating \"#{@registered_application.name}\". Please try again."
      render :edit
    end
  end

  def destroy
    @registered_application = RegisteredApplication.find(params[:id])
    if @registered_application.destroy
      flash[:notice] = "Removed \"#{@registered_application.name}\" successfully."
      redirect_to registered_applications_path
    else
      flash[:notice] = "There was an error removing \"#{@registered_application.name}\". Please try again."
      redirect_to @registered_application
    end
  end

  private

  def registered_application_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocmetrics</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <li></li>

      <div class="user-info pull-right nav-margin">
        <% if current_user %>
          Hello <%= link_to (current_user.name || current_user.email), registered_applications_path %>!
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-user"></span>
          <% end %>
          <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
            <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        <% else %>
          <%= link_to "Log In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>

    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <br>

    <%= yield %>
  </div>
</body>
</html>

app/views/registered_applications/_registered_application.html.erb
<h4><%= link_to registered_application.name, registered_application %></h4>

app/views/registered_applications/edit.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter application name" %>
      </div>

      <div class="form-group">
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/index.html.erb
<div class="row">
  <div class="col-md-8">
    <% if @registered_applications.any? %>
      <%= render @registered_applications %>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Register a new application", new_registered_application_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for @registered_application do |f| %>
      <div class="form-group">
        <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter application name" %>
      </div>

      <div class="form-group">
        <%= f.text_field :url, class: 'form-control', placeholder: "Enter application url" %>
      </div>

      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h2><%= @registered_application.name %></h2>
    <small><%= @registered_application.url %></small>
    <hr>
    <% if @registered_application.events.any? %>
      <h4>Events</h4>
      <%= pie_chart @registered_application.events.group(:name).count %>
      <%= line_chart @registered_application.events.group_by_day(:created_at).count %>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Update", edit_registered_application_path, class: 'btn btn-warning' %>
    <%= link_to "Remove", @registered_application, method: :delete, class: 'btn btn-danger', data: { confirm: "Removing #{@registered_application.name}. Are you sure?" } %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocmetrics</h1>
  <p>An analytics service to track events on websites.</p>
  <p>
    <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary' %>
    or
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
  </p>
</div>

<div class="row text-center">
  <div class="col-md-4">
    <h2>Track</h2>
    <p>events on your website</p>
  </div>
  <div class="col-md-4">
    <h2>Capture</h2>
    <p>and save those events to a database</p>
  </div>
  <div class="col-md-4">
    <h2>Display</h2>
    <p>the captured event data</p>
  </div>
</div>